version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
     # - checkout

      - run: git clone https://${GITHUB_TOKEN}@github.com/GuillaumeIsabelleX/ngtranslating-mastery.git .

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd ngapp && yarn install

        # GIT User setup so we can publish the Doc
      - run: git config --global user.email "jgi@jgwill.com" && git config --global user.name "Guillaume Isabelle"

        # Test and build, release the Docs
      - run: cd ngapp && yarn test && yarn release:docs

        # release:docs using ${GITHUB_TOKEN}
        # https://github.com/GuillaumeIsabelleX/ngtranslating-mastery.git
        # - run: git clone https://${GITHUB_TOKEN}@github.com/GuillaumeIsabelleX/ngtranslating-mastery.git


