version: 2
jobs:
  build:
    filters:    
      tags:
        only: /^v.*/

    docker:
      # specify the version you desire here
      - image: circleci/node:10-browsers



    working_directory: ~/repo

    steps:
     # - checkout

      - run: git clone https://${GITHUB_TOKEN}@github.com/GuillaumeIsabelleX/ngtranslating-mastery.git .
      - run:  git pull

      - run: mkdir -p docs
      - run: cd ngapp && yarn install

        # GIT User setup so we can publish the Doc
      - run: git config --global user.email "jgi@jgwill.com" && git config --global user.name "Guillaume Isabelle"

        # Test and build, release the Docs
      - run: ls ngapp/src/assets/i18n
      - run: pwd && ls docs
      - run: cd ngapp && yarn test
      # && yarn release:docs
      - run: rm -rf docs/* && echo "Docs cleaned"
      - run: pwd && ls docs
      - run: echo "Building in docs"
      - run: cd ngapp && yarn build:docs
      - run: pwd && ls docs
      - run: git add docs
      - run: git commit docs -m "docs updated by CircleCI" && git push

        # release:docs using ${GITHUB_TOKEN}
        # https://github.com/GuillaumeIsabelleX/ngtranslating-mastery.git
        # - run: git clone https://${GITHUB_TOKEN}@github.com/GuillaumeIsabelleX/ngtranslating-mastery.git


